<?php
namespace Gentle\Edith\Services;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class PaymentService extends ModelService
{
    /**
     * 定义模型名称
     * @var string|null
     */
    protected ?string $modelName = 'Gentle\Edith\Models\EdithPayment';

    /**
     * @return Builder
     */
    public function query(): Builder
    {
        return $this->model::query()->where('platform_id', app('edith.platform')->id());
    }

    protected function fillData(array $data): array
    {
        if (isset($data['method']) && is_string($data['method'])) {
            $data['method'] = explode(",", $data['method']);
        }
        return parent::fillData($data); // TODO: Change the autogenerated stub
    }
}