<?php
namespace Gentle\Edith\Services;

use Illuminate\Database\Eloquent\Builder;

class PlatformModelService extends ModelService
{
    /**
     * @return Builder
     */
    public function query(): Builder
    {
        return parent::query()->where('platform_id', app('edith.auth')->platformId()); // TODO: Change the autogenerated stub
    }
}