<?php
namespace Edith\Admin\Dao;

use Edith\Admin\Events\AttachmentDestroyBefore;
use Edith\Admin\Events\AttachmentUploadAfter;
use Edith\Admin\Events\AttachmentUploadBefore;
use Edith\Admin\Exceptions\DaoException;
use Edith\Admin\Models\EdithAttachment;
use Edith\Admin\Models\EdithAttachmentUse;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class AttachmentDao extends ModelDao
{
    /**
     * 定义模型名称
     * @var string|null
     */
    protected ?string $modelName = 'Edith\Admin\Models\EdithAttachment';

    /**
     * @return Builder
     * @throws \Edith\Admin\Exceptions\DaoException
     */
    public function query(): Builder
    {
        $query = parent::query(); // TODO: Change the autogenerated stub
        return $query->when(\request()->input('category_id'), function ($query) {
            $query->where('category_id', \request()->input('category_id'));
        });
    }

    /**
     * @param Request $request
     * @param int $platform_id
     * @return array|null
     * @throws DaoException
     */
    public function upfile(Request $request, int $platform_id = 0)
    {
        $before = new AttachmentUploadBefore($request, $platform_id);
        event($before); // 执行上传前事件，用于上传前的处理

        if (!($file = $before->file)) { // 如无工具模块事件存储文件 进行本地上传
            $file = $this->localUpload($request);
        }
        if (!isset($file['path']) && !isset($file['url'])) {
            throw new DaoException('上传失败');
        }

        if (!isset($file['id'])) { // 如果不存在模型索引ID 执行上传后事件
            $after = new AttachmentUploadAfter($request, $file, $platform_id);
            event($after);
            $result = [
                'id' => $after->fileId,
                'url' => $file['url'] ?? $file['path'],
                'size' => $file['size'],
                'name' => $file['name']
            ];
        } else {
            $result = $file;
        }
        return $result;
    }

    /**
     * 本地上传图片
     * @param Request $request
     * @return array
     * @throws \Edith\Admin\Exceptions\DaoException
     */
    protected function localUpload(Request $request): array
    {
        $file = $request->file('file') ?? $request->file('files');
        if (!$file) {
            throw new DaoException('不');
        }
        $md5 = md5_file($file->getRealPath());
        $name = $file->getClientOriginalName();

        $hasPicture = $this->query()->where('md5', $md5)->first();

        // 不存在文件，则插入数据库
        if (!$hasPicture) {
            $path = $file->store('uploads/attachments', 'public');
            // 获取文件大小
            $size = Storage::disk('public')->size($path);

            // 数据
            $data = [
                'category_id' => \request()->input('category_id', 0),
                'name' => $name,
                'size' => $size,
                'md5' => $md5,
                'ext' => $file->getClientOriginalExtension(),
                'mime' => $file->getClientMimeType(),
                'upload_ip' => \request()->ip(),
                'path' => $path,
                'url' => env('WEB_SITE_SSL', false) !== false ? secure_asset($path) : asset(Storage::url($path))
            ];
        } else {
            if (str_starts_with($hasPicture->path,'http')) {
                $url = $hasPicture->path;
            } else {
                // 获取文件url，用于外部访问
                $url = Storage::url($hasPicture->path);
            }

            $data = [
                'id' => $hasPicture->id,
                'name' => $name,
                'url' => env('WEB_SITE_SSL', false) !== false ? secure_asset($url) : asset($url),
                'size' => $hasPicture->size
            ];
        }

        // 返回数据
        return $data;
    }

    /**
     * @param $id
     * @return void
     * @throws DaoException
     */
    protected function deleting($id)
    {
        $ids = is_array($id) ? $id : [$id];
        foreach ($ids as $row) {
            $useInfo = EdithAttachmentUse::where('attachment_id', $row)->first();
            if ($useInfo) {
                throw new DaoException("附件模型占用中：{$useInfo['model']}_{$useInfo['model_id']}，无法删除，请更换后删除！");
            }
        }
        $models = EdithAttachment::whereIn('id', $ids)->get();
        try {
            $before = new AttachmentDestroyBefore($models);
            event($before);
        } catch (\Exception $e) {
            Log::warning("附件删除前事件执行异常：" . $e->getMessage()) ;
        }
        parent::deleting($id); // TODO: Change the autogenerated stub
    }
}