<?php
namespace Edith\Admin\Components\Fields\Item;

use Edith\Admin\Components\Fields\Field;
use Illuminate\Support\Collection;

/**
 * Ant ProFormList
 * https://pro-components.antdigital.dev/components/group#proformlist-api
 * @method self min(string|int $min)                                        最少条目，删除时如果当前数据条目少于该数则无法删除
 * @method self max(string|int $max)                                        最少条目，删除时如果当前数据条目少于该数则无法删除
 */
class FormList extends Field
{
    /**
     * @var string
     */
    public string $component = 'form-list';

    public Collection $items;

    public function __construct(?string $name = null, ?string $label = null)
    {
        parent::__construct($name, $label);
        $this->items = new Collection();
    }

    /**
     * @param array|Collection $items
     * @return self
     */
    public function items(array|Collection $items): self
    {
        if (is_array($items)) {
            $items = new Collection($items);
        }
        $this->items = $items;
        return $this;
    }

    /**
     * Item 中总是展示 label
     * @param bool $alwaysShowItemLabel
     * @return self
     */
    public function alwaysShowItemLabel(bool $alwaysShowItemLabel = true): self
    {
        return $this->set('alwaysShowItemLabel', $alwaysShowItemLabel);
    }

    /**
     * 复制按钮的配置，false 可以取消
     * @param bool|array $copyIconProps { Icon?: React.FC<any>; tooltipText?: string; } | false
     * @return self
     */
    public function copyIconProps(bool|array $copyIconProps = false): self
    {
        return $this->set('copyIconProps', $copyIconProps);
    }

    /**
     * 删除按钮的配置，false 可以取消
     * @param bool|array $deleteIconProps { Icon?: React.FC<any>; tooltipText?: string; } | false
     * @return self
     */
    public function deleteIconProps(bool|array $deleteIconProps = false): self
    {
        return $this->set('deleteIconProps', $deleteIconProps);
    }

    /**
     * 向上排序按钮的配置，false 可以取消
     * @param bool|array $upIconProps { Icon?: React.FC<any>; tooltipText?: string; } | false
     * @return self
     */
    public function upIconProps(bool|array $upIconProps = false): self
    {
        return $this->set('upIconProps', $upIconProps);
    }

    /**
     * 向下排序按钮的配置，false 可以取消
     * @param bool|array $downIconProps { Icon?: React.FC<any>; tooltipText?: string; } | false
     * @return self
     */
    public function downIconProps(bool|array $downIconProps = false): self
    {
        return $this->set('downIconProps', $downIconProps);
    }

    /**
     * 是否开启箭头按钮排序
     * @param bool $arrowSort
     * @return self
     */
    public function arrowSort(bool $arrowSort = true): self
    {
        return $this->set('arrowSort', $arrowSort);
    }

    /**
     * @return array
     */
    public function render(): array
    {
        unset($this->fieldProps);
        return parent::render(); // TODO: Change the autogenerated stub
    }
}