<?php
namespace Edith\Admin\Components\Forms;

use Edith\Admin\Components\Displays\TabPane;
use Edith\Admin\Components\Tabs\Tabs;
use Illuminate\Support\Collection;

class TabsForm extends ProForm
{
    /**
     * @var string
     */
    protected string $renderer = 'tabs-form';

    /**
     * 子标签页
     * @var Collection
     */
    protected Collection $tabs;

    /**
     * construct TabsForm
     */
    public function __construct()
    {
        parent::__construct();
        $this->tabs = new Collection;
    }

    /**
     * 子表单
     * @param string $label 标签 Label
     * @param null|array 子表单项
     * @return TabPane
     */
    public function tab(string $label, ?array $items = null): TabPane
    {
        return tap((new TabPane($label))->children($items), function ($value) {
            $this->tabs->push($value);
        });
    }

//    /**
//     * @return array
//     */
//    public function render(): array
//    {
//        $this->columns->push((new Tabs)->items($this->tabs));
//        unset($this->tabs);
//        return parent::render(); // TODO: Change the autogenerated stub
//    }
}